const videos = [
  {
    _id: "1",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://i.ytimg.com/vi/w7ejDZ8SWv8/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "A quick tutorial to get started with React.",
    channelName: "Code with John",
    views: 15200,
    likes: 1023,
    dislikes: 45,
    category: "Coding",
    comments: [
      {
        id: 1,
        user: "Rahul",
        text: "Great video! Very helpful.",
      },
    ],
  },
  {
    _id: "2",
    title: "Node.js Crash Course",
    thumbnailUrl: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Learn Node.js basics in one video.",
    channelName: "Tech World",
    views: 20300,
    likes: 950,
    dislikes: 20,
    category: "Coding",
    comments: [],
  },
  {
    _id: "3",
    title: "Top Gaming Highlights 2026",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Best gaming moments of the year.",
    channelName: "Gaming Hub",
    views: 40000,
    likes: 2100,
    dislikes: 60,
    category: "Gaming",
    comments: [],
  },
  {
    _id: "4",
    title: "Football Match Highlights",
    thumbnailUrl: "https://i.ytimg.com/vi/aqz-KE-bpKQ/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Amazing football highlights and goals.",
    channelName: "Sports Arena",
    views: 29800,
    likes: 1800,
    dislikes: 40,
    category: "Sports",
    comments: [],
  },
  {
    _id: "5",
    title: "Latest Tech News Today",
    thumbnailUrl: "https://i.ytimg.com/vi/ysz5S6PUM-U/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Today's top technology updates.",
    channelName: "News 24",
    views: 8900,
    likes: 400,
    dislikes: 15,
    category: "News",
    comments: [],
  },
  {
    _id: "6",
    title: "Best Study Tips for Students",
    thumbnailUrl: "https://i.ytimg.com/vi/jNQXAC9IVRw/maxresdefault.jpg",
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    description: "Useful study tips to improve learning.",
    channelName: "Study Smart",
    views: 17400,
    likes: 870,
    dislikes: 18,
    category: "Education",
    comments: [],
  },
];

export default videos;